DROP TABLE IF EXISTS CART;
CREATE TABLE CART (	
  CART_ID          NUMBER       NOT NULL,
	EMAIL            VARCHAR2(50) NOT NULL, 
	GOODS_ID         NUMBER(20)   NOT NULL, 
	CART_CNT         NUMBER(20)   NOT NULL, 
	
  PRIMARY KEY (CART_ID)
);

INSERT INTO CART VALUES(1, 'test@test.com', 1010001, 10);
