DROP TABLE IF EXISTS CART;
CREATE TABLE CART (	
  CART_ID          NUMBER       NOT NULL,
	EMAIL            VARCHAR2(50) NOT NULL, 
	GOODS_ID         NUMBER(20)   NOT NULL, 
	CART_CNT         NUMBER(20)   NOT NULL, 
	
  PRIMARY KEY (CART_ID)
);

INSERT INTO CART VALUES(1, 'test1@test.com', 1010001, 10);
INSERT INTO CART VALUES(2, 'test2@test.com', 1010002, 10);
INSERT INTO CART VALUES(3, 'test1@test.com', 1010003, 5);
